export const collection = (...args: any[]) => null;
export const getDocs = async (...args: any[]) => ({ empty: true, docs: [] as any[], forEach: (cb: any) => {} });
export const query = (...args: any[]) => null;
export const orderBy = (...args: any[]) => null;
export const limit = (...args: any[]) => null;
export const doc = (...args: any[]) => null;
export const setDoc = async (...args: any[]) => null;
export const serverTimestamp = () => new Date().toISOString();
export const addDoc = async (...args: any[]) => ({ id: Date.now().toString() });
export const getDoc = async (...args: any[]) => ({ exists: () => false, data: () => ({}) });
export const onSnapshot = (...args: any[]) => (() => {});
export const getDownloadURL = async (...args: any[]) => 'https://mock.url/file';
export const ref = (...args: any[]) => null;
export const uploadBytes = async (...args: any[]) => null;
export const deleteDoc = async (...args: any[]) => null;
export const deleteObject = async (...args: any[]) => null;
export const writeBatch = (...args: any[]) => ({ commit: async () => {}, set: () => {}, update: () => {}, delete: () => {} });
export const db = null;
export const auth = null;
export const storage = null;
